/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'archived' : IDL.Null,
});
export const Type__2 = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
export const Type__1 = IDL.Variant({
  'bag' : IDL.Null,
  'earbuds' : IDL.Null,
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'other' : IDL.Null,
  'keys' : IDL.Null,
  'laptop' : IDL.Null,
  'jewelry' : IDL.Null,
  'wallet' : IDL.Null,
  'books' : IDL.Null,
  'idCard' : IDL.Null,
  'phone' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'status' : Type,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'claimedByQR' : IDL.Bool,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isSecurityPatrol' : IDL.Bool,
  'qrClaimCode' : IDL.Opt(IDL.Text),
  'reportedBy' : IDL.Principal,
  'itemType' : Type__2,
  'category' : Type__1,
  'location' : IDL.Text,
  'photoId' : IDL.Opt(IDL.Text),
  'archivedAt' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'rewardPoints' : IDL.Nat,
  'email' : IDL.Text,
  'thanksReceived' : IDL.Nat,
  'isAdmin' : IDL.Bool,
});
export const FilterItemsInput = IDL.Record({
  'status' : IDL.Opt(Type),
  'dateTo' : IDL.Opt(IDL.Int),
  'itemType' : IDL.Opt(Type__2),
  'category' : IDL.Opt(Type__1),
  'dateFrom' : IDL.Opt(IDL.Int),
  'location' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const ReportItemInput = IDL.Record({
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'itemType' : Type__2,
  'category' : Type__1,
  'location' : IDL.Text,
  'photoId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'archiveExpiredItems' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSecurityRole' : IDL.Func([IDL.Principal], [], []),
  'awardThanks' : IDL.Func([IDL.Text], [], []),
  'claimByQR' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteItem' : IDL.Func([IDL.Text], [], []),
  'generateQRClaimCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getArchivedItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItemById' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getItems' : IDL.Func([FilterItemsInput], [IDL.Vec(Item)], ['query']),
  'getItemsByReporter' : IDL.Func([IDL.Principal], [IDL.Vec(Item)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMyItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'reportItem' : IDL.Func([ReportItemInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchItems' : IDL.Func(
      [IDL.Text, FilterItemsInput],
      [IDL.Vec(Item)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [], []),
  'setAdminRole' : IDL.Func([IDL.Principal], [], []),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateItemStatus' : IDL.Func([IDL.Text, Type], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Type__2 = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
  const Type__1 = IDL.Variant({
    'bag' : IDL.Null,
    'earbuds' : IDL.Null,
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'other' : IDL.Null,
    'keys' : IDL.Null,
    'laptop' : IDL.Null,
    'jewelry' : IDL.Null,
    'wallet' : IDL.Null,
    'books' : IDL.Null,
    'idCard' : IDL.Null,
    'phone' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'status' : Type,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'claimedByQR' : IDL.Bool,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isSecurityPatrol' : IDL.Bool,
    'qrClaimCode' : IDL.Opt(IDL.Text),
    'reportedBy' : IDL.Principal,
    'itemType' : Type__2,
    'category' : Type__1,
    'location' : IDL.Text,
    'photoId' : IDL.Opt(IDL.Text),
    'archivedAt' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'rewardPoints' : IDL.Nat,
    'email' : IDL.Text,
    'thanksReceived' : IDL.Nat,
    'isAdmin' : IDL.Bool,
  });
  const FilterItemsInput = IDL.Record({
    'status' : IDL.Opt(Type),
    'dateTo' : IDL.Opt(IDL.Int),
    'itemType' : IDL.Opt(Type__2),
    'category' : IDL.Opt(Type__1),
    'dateFrom' : IDL.Opt(IDL.Int),
    'location' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const ReportItemInput = IDL.Record({
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'itemType' : Type__2,
    'category' : Type__1,
    'location' : IDL.Text,
    'photoId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'archiveExpiredItems' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSecurityRole' : IDL.Func([IDL.Principal], [], []),
    'awardThanks' : IDL.Func([IDL.Text], [], []),
    'claimByQR' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteItem' : IDL.Func([IDL.Text], [], []),
    'generateQRClaimCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getArchivedItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItemById' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getItems' : IDL.Func([FilterItemsInput], [IDL.Vec(Item)], ['query']),
    'getItemsByReporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMyItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'reportItem' : IDL.Func([ReportItemInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchItems' : IDL.Func(
        [IDL.Text, FilterItemsInput],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [], []),
    'setAdminRole' : IDL.Func([IDL.Principal], [], []),
    'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateItemStatus' : IDL.Func([IDL.Text, Type], [], []),
  });
};

export const init = ({ IDL }) => { return []; };