/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FilterItemsInput {
  'status' : [] | [Type],
  'dateTo' : [] | [bigint],
  'itemType' : [] | [Type__2],
  'category' : [] | [Type__1],
  'dateFrom' : [] | [bigint],
  'location' : [] | [string],
}
export interface Item {
  'id' : string,
  'status' : Type,
  'title' : string,
  'contactInfo' : string,
  'claimedByQR' : boolean,
  'date' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'isSecurityPatrol' : boolean,
  'qrClaimCode' : [] | [string],
  'reportedBy' : Principal,
  'itemType' : Type__2,
  'category' : Type__1,
  'location' : string,
  'idCardPhotoId' : [] | [string],
  'photoId' : [] | [string],
  'archivedAt' : [] | [bigint],
}
export interface Message {
  'id' : string,
  'itemId' : string,
  'content' : string,
  'createdAt' : bigint,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
}
export interface Notification {
  'id' : string,
  'itemId' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
}
export interface ReportItemInput {
  'title' : string,
  'contactInfo' : string,
  'date' : bigint,
  'description' : string,
  'itemType' : Type__2,
  'category' : Type__1,
  'location' : string,
  'idCardPhotoId' : [] | [string],
  'photoId' : [] | [string],
}
export type Type = { 'resolved' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'archived' : null };
export type Type__1 = { 'bag' : null } |
  { 'earbuds' : null } |
  { 'clothing' : null } |
  { 'accessories' : null } |
  { 'other' : null } |
  { 'keys' : null } |
  { 'laptop' : null } |
  { 'jewelry' : null } |
  { 'wallet' : null } |
  { 'books' : null } |
  { 'idCard' : null } |
  { 'phone' : null };
export type Type__2 = { 'found' : null } |
  { 'lost' : null };
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : bigint,
  'rewardPoints' : bigint,
  'email' : string,
  'thanksReceived' : bigint,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveExpiredItems' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSecurityRole' : ActorMethod<[Principal], undefined>,
  'awardThanks' : ActorMethod<[string], undefined>,
  'claimByQR' : ActorMethod<[string, string], undefined>,
  'deleteItem' : ActorMethod<[string], undefined>,
  'generateQRClaimCode' : ActorMethod<[string], string>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getArchivedItems' : ActorMethod<[], Array<Item>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIdCardPhotoId' : ActorMethod<[string], [] | [string]>,
  'getItemById' : ActorMethod<[string], [] | [Item]>,
  'getItems' : ActorMethod<[FilterItemsInput], Array<Item>>,
  'getItemsByReporter' : ActorMethod<[Principal], Array<Item>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMyItems' : ActorMethod<[], Array<Item>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingItems' : ActorMethod<[], Array<Item>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'reportItem' : ActorMethod<[ReportItemInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchItems' : ActorMethod<[string, FilterItemsInput], Array<Item>>,
  'sendMessage' : ActorMethod<[string, Principal, string], undefined>,
  'setAdminRole' : ActorMethod<[Principal], undefined>,
  'setUserProfile' : ActorMethod<[string, string], undefined>,
  'updateItemStatus' : ActorMethod<[string, Type], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];