/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface FilterItemsInput {
    status?: Type;
    dateTo?: bigint;
    itemType?: Type__2;
    category?: Type__1;
    dateFrom?: bigint;
    location?: string;
}
export interface Item {
    id: string;
    status: Type;
    title: string;
    contactInfo: string;
    claimedByQR: boolean;
    date: bigint;
    createdAt: bigint;
    description: string;
    isSecurityPatrol: boolean;
    qrClaimCode?: string;
    reportedBy: Principal;
    itemType: Type__2;
    category: Type__1;
    location: string;
    idCardPhotoId?: string;
    photoId?: string;
    archivedAt?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Notification {
    id: string;
    itemId: string;
    userId: Principal;
    createdAt: bigint;
    isRead: boolean;
    message: string;
}
export interface ReportItemInput {
    title: string;
    contactInfo: string;
    date: bigint;
    description: string;
    itemType: Type__2;
    category: Type__1;
    location: string;
    idCardPhotoId?: string;
    photoId?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Message {
    id: string;
    itemId: string;
    content: string;
    createdAt: bigint;
    toPrincipal: Principal;
    fromPrincipal: Principal;
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    createdAt: bigint;
    rewardPoints: bigint;
    email: string;
    thanksReceived: bigint;
    isAdmin: boolean;
}
export enum Type {
    resolved = "resolved",
    active = "active",
    pending = "pending",
    rejected = "rejected",
    archived = "archived"
}
export enum Type__1 {
    bag = "bag",
    earbuds = "earbuds",
    clothing = "clothing",
    accessories = "accessories",
    other = "other",
    keys = "keys",
    laptop = "laptop",
    jewelry = "jewelry",
    wallet = "wallet",
    books = "books",
    idCard = "idCard",
    phone = "phone"
}
export enum Type__2 {
    found = "found",
    lost = "lost"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    archiveExpiredItems(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignSecurityRole(user: Principal): Promise<void>;
    awardThanks(itemId: string): Promise<void>;
    claimByQR(itemId: string, code: string): Promise<void>;
    deleteItem(itemId: string): Promise<void>;
    generateQRClaimCode(itemId: string): Promise<string>;
    getAllItems(): Promise<Array<Item>>;
    getArchivedItems(): Promise<Array<Item>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIdCardPhotoId(itemId: string): Promise<string | null>;
    getItemById(itemId: string): Promise<Item | null>;
    getItems(filters: FilterItemsInput): Promise<Array<Item>>;
    getItemsByReporter(reporter: Principal): Promise<Array<Item>>;
    getMessages(itemId: string): Promise<Array<Message>>;
    getMyItems(): Promise<Array<Item>>;
    getNotifications(): Promise<Array<Notification>>;
    getPendingItems(): Promise<Array<Item>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(notificationId: string): Promise<void>;
    reportItem(input: ReportItemInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchItems(searchTerm: string, filters: FilterItemsInput): Promise<Array<Item>>;
    sendMessage(itemId: string, toPrincipal: Principal, content: string): Promise<void>;
    setAdminRole(user: Principal): Promise<void>;
    setUserProfile(displayName: string, email: string): Promise<void>;
    updateItemStatus(itemId: string, status: Type): Promise<void>;
}
import type { FilterItemsInput as _FilterItemsInput, Item as _Item, ReportItemInput as _ReportItemInput, Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async archiveExpiredItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveExpiredItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveExpiredItems();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignSecurityRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSecurityRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSecurityRole(arg0);
            return result;
        }
    }
    async awardThanks(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardThanks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardThanks(arg0);
            return result;
        }
    }
    async claimByQR(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimByQR(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimByQR(arg0, arg1);
            return result;
        }
    }
    async deleteItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async generateQRClaimCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQRClaimCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQRClaimCode(arg0);
            return result;
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArchivedItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedItems();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedItems();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdCardPhotoId(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdCardPhotoId(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdCardPhotoId(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemById(arg0: string): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItems(arg0: FilterItemsInput): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItems(to_candid_FilterItemsInput_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItems(to_candid_FilterItemsInput_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByReporter(arg0: Principal): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByReporter(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByReporter(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyItems();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyItems();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getPendingItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingItems();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingItems();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async reportItem(arg0: ReportItemInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportItem(to_candid_ReportItemInput_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportItem(to_candid_ReportItemInput_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchItems(arg0: string, arg1: FilterItemsInput): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItems(arg0, to_candid_FilterItemsInput_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItems(arg0, to_candid_FilterItemsInput_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminRole(arg0);
            return result;
        }
    }
    async setUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0, arg1);
            return result;
        }
    }
    async updateItemStatus(arg0: string, arg1: Type): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItemStatus(arg0, to_candid_Type_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItemStatus(arg0, to_candid_Type_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Item_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Type;
    title: string;
    contactInfo: string;
    claimedByQR: boolean;
    date: bigint;
    createdAt: bigint;
    description: string;
    isSecurityPatrol: boolean;
    qrClaimCode: [] | [string];
    reportedBy: Principal;
    itemType: _Type__2;
    category: _Type__1;
    location: string;
    idCardPhotoId: [] | [string];
    photoId: [] | [string];
    archivedAt: [] | [bigint];
}): {
    id: string;
    status: Type;
    title: string;
    contactInfo: string;
    claimedByQR: boolean;
    date: bigint;
    createdAt: bigint;
    description: string;
    isSecurityPatrol: boolean;
    qrClaimCode?: string;
    reportedBy: Principal;
    itemType: Type__2;
    category: Type__1;
    location: string;
    idCardPhotoId?: string;
    photoId?: string;
    archivedAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Type_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contactInfo: value.contactInfo,
        claimedByQR: value.claimedByQR,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        isSecurityPatrol: value.isSecurityPatrol,
        qrClaimCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.qrClaimCode)),
        reportedBy: value.reportedBy,
        itemType: from_candid_Type__2_n16(_uploadFile, _downloadFile, value.itemType),
        category: from_candid_Type__1_n18(_uploadFile, _downloadFile, value.category),
        location: value.location,
        idCardPhotoId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.idCardPhotoId)),
        photoId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.photoId)),
        archivedAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.archivedAt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    archived: null;
}): Type {
    return "resolved" in value ? Type.resolved : "active" in value ? Type.active : "pending" in value ? Type.pending : "rejected" in value ? Type.rejected : "archived" in value ? Type.archived : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: null;
} | {
    lost: null;
}): Type__2 {
    return "found" in value ? Type__2.found : "lost" in value ? Type__2.lost : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bag: null;
} | {
    earbuds: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    keys: null;
} | {
    laptop: null;
} | {
    jewelry: null;
} | {
    wallet: null;
} | {
    books: null;
} | {
    idCard: null;
} | {
    phone: null;
}): Type__1 {
    return "bag" in value ? Type__1.bag : "earbuds" in value ? Type__1.earbuds : "clothing" in value ? Type__1.clothing : "accessories" in value ? Type__1.accessories : "other" in value ? Type__1.other : "keys" in value ? Type__1.keys : "laptop" in value ? Type__1.laptop : "jewelry" in value ? Type__1.jewelry : "wallet" in value ? Type__1.wallet : "books" in value ? Type__1.books : "idCard" in value ? Type__1.idCard : "phone" in value ? Type__1.phone : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n11(_uploadFile, _downloadFile, x));
}
function to_candid_FilterItemsInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilterItemsInput): _FilterItemsInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ReportItemInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportItemInput): _ReportItemInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Type__2_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): _Type__2 {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Type;
    dateTo?: bigint;
    itemType?: Type__2;
    category?: Type__1;
    dateFrom?: bigint;
    location?: string;
}): {
    status: [] | [_Type];
    dateTo: [] | [bigint];
    itemType: [] | [_Type__2];
    category: [] | [_Type__1];
    dateFrom: [] | [bigint];
    location: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_Type_n27(_uploadFile, _downloadFile, value.status)) : candid_none(),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        itemType: value.itemType ? candid_some(to_candid_Type__2_n29(_uploadFile, _downloadFile, value.itemType)) : candid_none(),
        category: value.category ? candid_some(to_candid_Type__1_n31(_uploadFile, _downloadFile, value.category)) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contactInfo: string;
    date: bigint;
    description: string;
    itemType: Type__2;
    category: Type__1;
    location: string;
    idCardPhotoId?: string;
    photoId?: string;
}): {
    title: string;
    contactInfo: string;
    date: bigint;
    description: string;
    itemType: _Type__2;
    category: _Type__1;
    location: string;
    idCardPhotoId: [] | [string];
    photoId: [] | [string];
} {
    return {
        title: value.title,
        contactInfo: value.contactInfo,
        date: value.date,
        description: value.description,
        itemType: to_candid_Type__2_n29(_uploadFile, _downloadFile, value.itemType),
        category: to_candid_Type__1_n31(_uploadFile, _downloadFile, value.category),
        location: value.location,
        idCardPhotoId: value.idCardPhotoId ? candid_some(value.idCardPhotoId) : candid_none(),
        photoId: value.photoId ? candid_some(value.photoId) : candid_none()
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    archived: null;
} {
    return value == Type.resolved ? {
        resolved: null
    } : value == Type.active ? {
        active: null
    } : value == Type.pending ? {
        pending: null
    } : value == Type.rejected ? {
        rejected: null
    } : value == Type.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): {
    found: null;
} | {
    lost: null;
} {
    return value == Type__2.found ? {
        found: null
    } : value == Type__2.lost ? {
        lost: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    bag: null;
} | {
    earbuds: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    keys: null;
} | {
    laptop: null;
} | {
    jewelry: null;
} | {
    wallet: null;
} | {
    books: null;
} | {
    idCard: null;
} | {
    phone: null;
} {
    return value == Type__1.bag ? {
        bag: null
    } : value == Type__1.earbuds ? {
        earbuds: null
    } : value == Type__1.clothing ? {
        clothing: null
    } : value == Type__1.accessories ? {
        accessories: null
    } : value == Type__1.other ? {
        other: null
    } : value == Type__1.keys ? {
        keys: null
    } : value == Type__1.laptop ? {
        laptop: null
    } : value == Type__1.jewelry ? {
        jewelry: null
    } : value == Type__1.wallet ? {
        wallet: null
    } : value == Type__1.books ? {
        books: null
    } : value == Type__1.idCard ? {
        idCard: null
    } : value == Type__1.phone ? {
        phone: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
